config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :welcomes
  resources :sections
  resources :feedbacks
  resources :faqs
  resources :contacts
  resources :banners
  resources :boards
  resources :blogs
  resources :features
  resources :services
  resources :abouts
  resources :headers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  root "welcomes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :abtimg, AbtimgUploader

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :bannerimg, BannerimgUploader

end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blogimg, BlogimgUploader


end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :boardimg, BoardimgUploader

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord

end

app/models/feature.rb
class Feature < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :fimg, FimgUploader

end

app/models/feedback.rb
class Feedback < ApplicationRecord


end

app/models/header.rb
class Header < ApplicationRecord
  mount_uploader :headerimg, HeaderimgUploader

end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :serviceimg, ServiceimgUploader

end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/welcome.rb
class Welcome < ApplicationRecord
  mount_uploader :logoimg, LogoimgUploader

end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base

  before_action :find_faqs, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_adminuser!, except: [:index, :show]
  def index
    @faqs = Faq.all.order('created_at DESC')
    @headers = Header.all

  end

  def show
  end

  private
  def find_faqs
    @faq = Faq.find(params[:id])
  end
  def faqs_param
      params.require(:faq).permit(:title, :body)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/faqs/index.html.erb
<!--Page Title-->
<% if Header.exists? %>
<% @headers.take(1).each do |h| %>
<section class="page-title" style="background-image:url(<%= h.headerimg_url.to_s %>);">
    <div class="auto-container clearfix">
        <h1>  FAQ'S</h1>
        <ul class="bread-crumb clearfix">
          <li><%= link_to "Home", root_path  %></li>
            <li>  Faq's
</li>
        </ul>
    </div>
</section>
<% end %>
<% else %>
<section class="page-title" style="background-image:url(<%= asset_path "background/7.jpg"%>);">
    <div class="auto-container clearfix">
        <h1>  FAQ'S
</h1>
        <ul class="bread-crumb clearfix">
            <li><a href="index-2.html">Home</a></li>
            <li>  Faq's
</li>
        </ul>
    </div>
</section>
<% end %>
<%= render "shared/faqs" %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @faq.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @faq.body %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>