config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :welcomes
  resources :sections
  resources :feedbacks
  resources :faqs
  resources :contacts
  resources :banners
  resources :boards
  resources :blogs
  resources :features
  resources :services
  resources :abouts
  resources :headers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  root "welcomes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :abtimg, AbtimgUploader

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :bannerimg, BannerimgUploader

end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blogimg, BlogimgUploader


end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :boardimg, BoardimgUploader

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord

end

app/models/feature.rb
class Feature < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :fimg, FimgUploader

end

app/models/feedback.rb
class Feedback < ApplicationRecord


end

app/models/header.rb
class Header < ApplicationRecord
  mount_uploader :headerimg, HeaderimgUploader

end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :serviceimg, ServiceimgUploader

end

app/models/team.rb
class Team < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/welcome.rb
class Welcome < ApplicationRecord
  mount_uploader :logoimg, LogoimgUploader

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%  @welcomes = Welcome.all  %>
  <% @welcomes.take(1).each do |w| %>
  <title>Jaiz Global  || <%=w.title %> </title>
  <meta name="description" content="<%= w.desc %>">
  <% end %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Responsive -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
  <!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
  <!--Start of Tawk.to Script-->
  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/5efaa2fe9e5f694422918c46/default';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);
  })();
  </script>
  <!--End of Tawk.to Script-->
  <!--End of Tawk.to Script-->
  <meta name="theme-color" content="#ffffff">
</head>

<body>

  <% unless flash.empty? %>
 <script type="text/javascript">
     <% flash.each do |f| %>
     <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
     <% end %>
 </script>
<% end %>
<% @abouts = About.all.order('created_at DESC') %>
<% @services = Service.all.order('created_at DESC') %>
<% @welcomes = Welcome.all %>
<% @headers = Header.all %>
<%     @sections = Section.all.order('created_at DESC')
 %>

  <div class="page-wrapper">

  <%= render "shared/header" %>

  <%= yield %>
  <%= render "shared/footer" %>
  </div>
  <%= javascript_include_tag 'script' %>


  </body>
</html>

app/views/shared/_abouts.html.erb
<!-- About Us -->
<section class="about-us">
    <div class="auto-container">
        <div class="row clearfix">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                  <% if Header.exists? %>
                  <% @headers.take(1).each do |h| %>
                  <div class="sec-title">
                    <h2><%= h.abouts_title %></h2>
                  </div>
                  <div class="text-box">
                    <p><%= h.abouts_sub_title %></p>
                  </div>
                  <% end %>
                  <% else %>
                  <div class="sec-title">
                      <h2>About Us</h2>
                  </div>
                  <div class="about-years"><span class="years">35</span><h3>Years Of Experience</h3></div>
                  <div class="text-box">
                      <p>Our commitment to bring <a href="#">professionalism</a>, good service & trust to the home repair service & maintenance business. We take immense pride in sending some of the most of professional handymen to yours homes to fix things that aren't workings. </p>
                  </div>
                  <% end %>



                    <ul class="list-style-one">
                      <% if About.exists?%>

                      <% @abouts.take(3).each do |a| %>
                      <li><%= a.title %>.</li>

                      <% end %>
                      <% else %>

                        <li>Quis nostrud exer citation.</li>
                        <li>Exercitation ullamco laboris nis.</li>
                        <li>Commodo consequat duis autex.</li>
                        <% end %>
                    </ul>
                    <div class="bottom-box clearfix">
                        <div class="btn-box">
                          <%= link_to abouts_path, class: "theme-btn btn-style-one" do %>
                            <span class="btn-title">Read More</span><span></span><span></span><span></span><span></span>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <% if About.exists? %>
                <% @abouts.take(1).each do |a| %>
                <div class="inner-column">
                    <div class="video-box wow fadeIn">
                        <figure class="image"><img src="<%= a.abtimg_url.to_s %>" alt=""></figure>
                    </div>
                </div>
                <% end %>
                <% else %>
                <div class="inner-column">
                    <div class="video-box wow fadeIn">
                        <figure class="image"><img src="<%= asset_path "resource/about-us.jpg"%>" alt=""></figure>
                    </div>
                </div>
                <% end %>
            </div>

        </div>
    </div>
</section>
<!-- End About Us -->

app/views/shared/_banner.html.erb
<% if Banner.exists? %>
<section class="banner-section">
    <div class="banner-carousel owl-carousel owl-theme">
        <!-- Slide Item -->
        <% @banners.each do |b| %>
        <div class="slide-item">
            <div class="image-layer" style="background-image:url(<%= b.bannerimg_url.to_s %>)"></div>
            <div class="content-box">
                <div class="content">
                    <div class="auto-container">
                        <h2><%= b.title %></h2>
                        <div class="text"><%= b.sub_title %></div>
                        <div class="btn-box">
                            <%= link_to new_contact_path, class: "theme-btn btn-style-two" do %>
                            <span class="btn-title">Learn More </span><span></span><span></span><span></span><span></span>

                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>

    </div>
</section>
<% else %>

<section class="banner-section">
    <div class="banner-carousel owl-carousel owl-theme">
        <!-- Slide Item -->
        <div class="slide-item">
            <div class="image-layer" style="background-image:url('<%= asset_path "main-slider/1.jpg"%>')"></div>
            <div class="content-box">
                <div class="content">
                    <div class="auto-container">
                        <span class="title">Welcome To Wooder</span>
                        <h2>Quality Wooden<br> On Your Demond</h2>
                        <div class="text">From 1984, we have worked tirelessly to earan our reputation for <br>quality and dependability in all wooden products we offer.</div>
                        <div class="btn-box">
                            <a href="#" class="theme-btn btn-style-two"><span class="btn-title">Check Service</span><span></span><span></span><span></span><span></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Slide Item -->
        <div class="slide-item">
          <div class="image-layer" style="background-image:url('<%= asset_path "main-slider/2.jpg"%>')"></div>
            <div class="content-box">
                <div class="content">
                    <div class="auto-container">
                        <span class="title">Welcome To Wooder</span>
                        <h2>We give solution to<br> need your carpenter</h2>
                        <div class="text">From 1984, we have worked tirelessly to earan our reputation for <br>quality and dependability in all wooden products we offer.</div>
                        <div class="btn-box">
                            <a href="#" class="theme-btn btn-style-two"><span class="btn-title">Check Service</span><span></span><span></span><span></span><span></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<% end %>

app/views/shared/_body.html.erb
<%= render "shared/banner" %>
<%= render "shared/abouts" %>
<%= render "shared/services" %>
<%= render "shared/features" %>
<%= render "shared/board" %>
<%= render "shared/feedbacks" %>
<%= render "shared/blogs" %>

app/views/shared/_ctr.html.erb
<!-- Start CTR Area -->
<% if Section.exists? %>
<% @sections.take(1).each do |s| %>
<section class="ctr-area">
    <div class="container">
        <div class="ctr-content">
            <h2><%= s.title %></h2>
            <p><%= s.body %></p>
            <%= link_to s, class: "default-btn"  do %>
        Get a Quote <i class="flaticon-right-chevron"></i><span></span><% end %>
        </div>

        <div class="ctr-image">
            <img src="<%= asset_path "ctr-img.jpg"%>" alt="image">
        </div>

        <div class="shape">
            <img src="<%= asset_path "bg-dot3.png" %>" alt="image">
        </div>
    </div>
</section>
<%end %>
<% else %>
<section class="ctr-area">
    <div class="container">
        <div class="ctr-content">
            <h2>Insurances for your child's future</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
            <a href="#" class="default-btn">Get a Quote <i class="flaticon-right-chevron"></i><span></span></a>
        </div>

        <div class="ctr-image">
            <img src="<%= asset_path "ctr-img.jpg"%>" alt="image">
        </div>

        <div class="shape">
            <img src="<%= asset_path "bg-dot3.png" %>" alt="image">
        </div>
    </div>
</section>
<!-- End CTR Area -->
<% end %>

app/views/shared/_footer.html.erb
<footer class="main-footer" style="background-image: url(<%= asset_path "background/12.png" %>);">
  <div class="auto-container">
    <!--Widgets Section-->
    <div class="widgets-section">
      <div class="row">
        <!--Footer Column-->
        <div class="footer-column col-xl-4 col-lg-5 col-md-12 col-sm-12">
          <% if Welcome.exists? %>
          <% @welcomes.each do |w| %>
          <div class="footer-widget about-widget">
            <div class="footer-logo">
              <figure class="image">
                <%= link_to w do %>
                <%= image_tag w.logoimg_url.to_s %>
                <% end %>
              </figure>                      </div>
              <div class="widget-content">
                <div class="text"><%= w.desc %></div>
                <ul class="contact-list">
                  <li><span class="fa fa-map-marker"></span> <%= w.address %>.</li>
                  <li><span class="fa fa-envelope"></span> <a href="mailto:<%= w.footer %>"><%= w.footer %></a></li>
                  <li><span class="fa fa-phone-volume"></span><a href="tel:<%= w.phone %>"><%= w.phone %></a></li>
                </ul>
              </div>
            </div>
            <% end %>
            <% else %>

            <div class="footer-widget about-widget">
              <div class="footer-logo">
                <figure class="image"><a href="index-2.html"><img src="<%= asset_path "logo-2.png" %>" alt=""></a></figure>
              </div>
              <div class="widget-content">
                <div class="text">We have over 10 years of experience, We take pride in delivering Intelligent Designs for clients all over the World.</div>
                <ul class="contact-list">
                  <li><span class="fa fa-map-marker"></span> 256 Interior the good, New York.</li>
                  <li><span class="fa fa-envelope"></span> <a href="mailto:Supportyou@demo.com">Support@demo.com</a></li>
                  <li><span class="fa fa-phone-volume"></span><a href="tel:1-800-985-357">1-800-985-357</a></li>
                </ul>
              </div>
            </div>
            <% end %>

          </div>

          <!--Footer Column-->
          <div class="footer-column col-xl-5 col-lg-7 col-md-12 col-sm-12">
            <!--Footer Column-->
            <div class="footer-widget links-widget">
              <div class="row">
                <div class="col-lg-7 col-md-6">
                  <h2 class="widget-title">Services</h2>
                  <!--Footer Column-->
                  <div class="widget-content">
                    <ul class="list-style-two">
                      <% if Service.exists? %>
                      <% @services.each do |a| %>
                      <li>
                        <%= link_to a.title, a %>
                      </li>
                      <% end %>
                      <% else %>
                      <li><a href="services.html">All Services</a></li>
                      <li><a href="service-detail.html">General Carpentry</a></li>
                      <li><a href="service-detail.html">Furniture Remod..</a></li>
                      <li><a href="service-detail.html">Hang Paintings</a></li>
                      <li><a href="service-detail.html">Manufactur Furni..</a></li>
                      <li><a href="service-detail.html">Commercial work</a></li>
                      <li><a href="service-detail.html">Furniture Design</a></li>
                      <% end %>
                    </ul>
                  </div>
                </div>

                <div class="col-lg-5 col-md-6">
                  <h3 class="widget-title">Useful Links</h3>
                  <!--Footer Column-->
                  <div class="widget-content">
                    <ul class="list-style-two">
                      <% if About.exists? %>
                      <% @abouts.each do |a| %>
                      <li>
                        <%= link_to a.title, a %>
                      </li>
                      <% end %>
                      <li><%= link_to "News Updates", blogs_path %></li>
                      <li><%= link_to "Faq", faqs_path %></li>

                      <% else %>
                      <li><a href="services.html">About Us</a></li>
                      <li><a href="service-detail.html">Team</a></li>
                      <li><a href="service-detail.html">Pricing</a></li>
                      <li><a href="service-detail.html">FAQ's</a></li>
                      <li><a href="service-detail.html">Portfolio</a></li>
                      <li><a href="service-detail.html">Subscribe</a></li>
                      <li><a href="service-detail.html">Contact Us</a></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!--Footer Column-->
          <div class="footer-column col-xl-3 col-lg-6 col-md-12 col-sm-12">
            <div class="footer-widget subscribe-widget">
              <h2 class="widget-title">Socials</h2>
              <div class="widget-content">


                <ul class="social-links">
                  <% @welcomes.each do |w| %>

                  <li><a href="<%= w.twitter%>"><i class="fab fa-twitter"></i></a></li>
                  <li><a href="<%= w.footer%>"><i class="fab fa-google-plus-g"></i></a></li>
                  <li><a href="<%= w.ln %>"><i class="fab fa-linkedin-in"></i></a></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!--Footer Bottom-->
    <div class="footer-bottom">
      <div class="auto-container">
        <div class="copyright-text">Copyrights 2019. All Rights are Reserved by <a href="#">JAIZ GLOBAL LLC</a></div>
      </div>
    </div>
  </footer>
  <!-- End Main Footer -->

app/views/shared/_header.html.erb
<% if Welcome.exists? %>
<header class="main-header">
  <!--Header Top-->
  <% @welcomes.each do |w| %>
  <div class="header-top">
    <div class="auto-container clearfix">
      <div class="top-left">
        <div class="text"><%= w.title %>.</div>
      </div>

      <div class="top-right">
        <ul class="contact-info clearfix">
          <li><span class="icon fa fa-phone-volume"></span> <a href="tel:<%= w.phone%>"><%= w.phone%></a></li>
          <li><span class="icon fa fa-envelope"></span> <a href="mailto:<%= w.footer%>"><%= w.footer%></a></li>
          <!--Search Box-->

        </ul>
        <ul class="social-icon-one clearfix">
          <li><a href="<%= w.twitter%>"><i class="fab fa-twitter"></i></a></li>
          <li><a href="<%= w.footer%>"><i class="fab fa-google-plus-g"></i></a></li>
          <li><a href="<%= w.ln %>"><i class="fab fa-linkedin-in"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <% end %>
  <!-- End Header Top -->

  <!--Header Lower-->
  <div class="header-lower">
    <div class="auto-container">
      <div class="main-box clearfix">
        <div class="pull-left logo-outer">
          <% @welcomes.take(1).each do |w| %>
          <div class="logo">
            <%= link_to root_path do %>
            <%= image_tag (w.logoimg_url.to_s) %>
            <% end %>

          </div>
          <% end %>
        </div>

        <!--Nav Box-->
        <div class="nav-outer clearfix">
          <!--Mobile Navigation Toggler-->
          <div class="mobile-nav-toggler"><span class="icon flaticon-menu"></span></div>

          <!-- Main Menu -->
          <nav class="main-menu navbar-expand-md navbar-light">
            <div class="collapse navbar-collapse clearfix" id="navbarSupportedContent">
              <ul class="navigation clearfix">
                <li class="current ">
                    <%= link_to root_path do %>
                    Home
                    <% end %>

                </li>
                <li class="dropdown"><a href="#">Knowledge Base</a>
                  <ul>
                    <% @abouts.each do |a| %>
                    <li>
                      <%= link_to a.title, a %>
                    </li>
                    <% end %>
                    <li >
                      <%= link_to "FAQ's", faqs_path %>

                    </li>
                    <li >
                      <%= link_to "Board Of Directors", boards_path %>

                    </li>
                    <li >
                      <%= link_to "Management Team", teams_path %>

                    </li>

                  </ul>
                </li>
                <li class="dropdown"><a href="#">Services</a>
                  <ul>
                    <% @services.each do |a| %>
                    <li>
                      <%= link_to a.title, a %>
                    </li>
                    <% end %>
                  </ul>
                </li>

                <li><%= link_to "News Updates", blogs_path %></li>
              </ul>
            </div>
          </nav>
          <!-- Main Menu End-->

          <div class="outer-box">
            <!-- Shoppping Car -->

            <!-- Btn Box -->
            <div class="btn-box">
              <%= link_to  new_contact_path, class: "theme-btn btn-style-one" do %>
           <span class="btn-title">Appointment</span> <span></span><span></span><span></span><span></span>
           <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--End Header Lower-->
<% @welcomes.take(1).each do |w| %>
  <!-- Sticky Header  -->
  <div class="sticky-header">
    <div class="auto-container clearfix">
      <!--Logo-->
      <div class="logo pull-left">
        <%= link_to root_path do %>
        <%= image_tag w.logoimg_url.to_s %>
        <% end %>
            </div>
      <!--Right Col-->
      <div class="nav-outer pull-right">
        <!--Mobile Navigation Toggler-->
        <div class="mobile-nav-toggler"><span><i class="fas fa-ellipsis-v"></i></span></div>

        <!-- Main Menu -->
        <nav class="main-menu">
          <div class="navbar-collapse show collapse clearfix">
            <ul class="navigation clearfix"><!--Keep This Empty / Menu will come through Javascript--></ul>
          </div>
        </nav><!-- Main Menu End-->
      </div>
    </div>
  </div><!-- End Sticky Menu -->


  <!-- Mobile Menu  -->
  <div class="mobile-menu">
    <div class="menu-backdrop"></div>
    <div class="close-btn"><span class="icon flaticon-cancel-1"></span></div>

    <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
    <nav class="menu-box">
      <div class="nav-logo">
        <%= link_to root_path do %>
        <%= image_tag w.logoimg_url.to_s %>
        <% end %>
            </div>

      <ul class="navigation clearfix"><!--Keep This Empty / Menu will come through Javascript--></ul>
    </nav>
  </div><!-- End Mobile Menu -->
  <% end %>
</header>

<% else %>
<header class="main-header">
  <!--Header Top-->
  <div class="header-top">
    <div class="auto-container clearfix">
      <div class="top-left">
        <div class="text">Welcome to Wooder Interior decoration Solution.</div>
      </div>

      <div class="top-right">
        <ul class="contact-info clearfix">
          <li><span class="icon fa fa-phone-volume"></span> <a href="tel:590780123">590 780 123</a></li>
          <li><span class="icon fa fa-envelope"></span> <a href="mailto:demo@wooder.com">demo@wooder.com</a></li>
          <!--Search Box-->

        </ul>
        <ul class="social-icon-one clearfix">
          <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
          <li><a href="#"><i class="fab fa-twitter"></i></a></li>
          <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
          <li><a href="#"><i class="fab fa-skype"></i></a></li>
          <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- End Header Top -->

  <!--Header Lower-->
  <div class="header-lower">
    <div class="auto-container">
      <div class="main-box clearfix">
        <div class="pull-left logo-outer">
          <div class="logo"><a href="index-2.html"><img src="<%= asset_path "logo.png" %>" alt="" title=""></a></div>
        </div>

        <!--Nav Box-->
        <div class="nav-outer clearfix">
          <!--Mobile Navigation Toggler-->
          <div class="mobile-nav-toggler"><span class="icon flaticon-menu"></span></div>

          <!-- Main Menu -->
          <nav class="main-menu navbar-expand-md navbar-light">
            <div class="collapse navbar-collapse clearfix" id="navbarSupportedContent">
              <ul class="navigation clearfix">
                <li class="current dropdown"><a href="index-2.html">Home</a>
                  <ul>
                    <li class="dropdown"><a href="#">Header Styles</a>
                      <ul>
                        <li><a href="index-2.html">Header Style One</a></li>
                        <li><a href="index-3.html">Header Style Two</a></li>
                        <li><a href="index-4.html">Header Style Three</a></li>
                        <li><a href="index-5.html">Header Style Four</a></li>
                      </ul>
                    </li>
                    <li><a href="index-2.html">Home Style One</a></li>
                    <li><a href="index-3.html">Home Style Two</a></li>
                    <li><a href="index-4.html">Home Style Three</a></li>
                    <li><a href="index-5.html">Home One Pager</a></li>
                    <li><a href="index-6.html">Home Video Banner</a></li>
                  </ul>
                </li>
                <li class="dropdown"><a href="about.html">About</a>
                  <ul>
                    <li><a href="about.html">About Us</a></li>
                    <li><a href="faqs.html">FAQ's</a></li>
                    <li><a href="team.html">Team</a></li>
                    <li><a href="pricing.html">Pricing</a></li>
                    <li><a href="coming-soon.html">Coming Soon</a></li>
                  </ul>
                </li>
                <li class="dropdown"><a href="services.html">Services</a>
                  <ul>
                    <li><a href="services.html">All Services</a></li>
                    <li><a href="service-detail.html">General Carpentry</a></li>
                    <li><a href="service-detail.html">Furniture Remodeling</a></li>
                    <li><a href="service-detail.html">Hang Paintings</a></li>
                    <li><a href="service-detail.html">Manufactur Furniture</a></li>
                    <li><a href="service-detail.html">Commercial work</a></li>
                    <li><a href="service-detail.html">Furniture Design</a></li>
                  </ul>
                </li>
                <li class="dropdown"><a href="projects.html">Projects</a>
                  <ul>
                    <li><a href="projects.html">Projects</a></li>
                    <li><a href="project-detail.html">Project Detail</a></li>
                  </ul>
                </li>
                <li class="dropdown"><a href="blog.html">Blog</a>
                  <ul>
                    <li><a href="blog.html">Blog with Sidebar</a></li>
                    <li><a href="blog-grid.html">Blog Grid View</a></li>
                    <li><a href="blog-detail.html">Blog Detail</a></li>
                    <li><a href="error-page.html">404 Error</a></li>
                  </ul>
                </li>
                <li class="dropdown"><a href="#">Shop</a>
                  <ul>
                    <li><a href="shop.html">Shop</a></li>
                    <li><a href="shop-single.html">Product Details</a></li>
                    <li><a href="shopping-cart.html">Cart Page</a></li>
                    <li><a href="checkout.html">Checkout Page</a></li>
                    <li><a href="login.html">Registration Page</a></li>
                  </ul>
                </li>
                <li><a href="contact.html">Contact</a></li>
              </ul>
            </div>
          </nav>
          <!-- Main Menu End-->

          <div class="outer-box">
            <!-- Shoppping Car -->
            <div class="cart-btn">
              <a href="#"><i class="icon flaticon-shopping-bag"></i> <span class="count">2</span></a>
            </div>

            <!-- Btn Box -->
            <div class="btn-box">
              <a href="contact.html" class="theme-btn btn-style-one"><span class="btn-title">Appointment</span> <span></span><span></span><span></span><span></span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--End Header Lower-->

  <!-- Sticky Header  -->
  <div class="sticky-header">
    <div class="auto-container clearfix">
      <!--Logo-->
      <div class="logo pull-left">
        <a href="index-2.html" title=""><img src="<%= asset_path "logo.png" %>" alt="" title=""></a>
      </div>
      <!--Right Col-->
      <div class="nav-outer pull-right">
        <!--Mobile Navigation Toggler-->
        <div class="mobile-nav-toggler"><span class="icon flaticon-menu"></span></div>

        <!-- Main Menu -->
        <nav class="main-menu">
          <div class="navbar-collapse show collapse clearfix">
            <ul class="navigation clearfix"><!--Keep This Empty / Menu will come through Javascript--></ul>
          </div>
        </nav><!-- Main Menu End-->
      </div>
    </div>
  </div><!-- End Sticky Menu -->


  <!-- Mobile Menu  -->
  <div class="mobile-menu">
    <div class="menu-backdrop"></div>
    <div class="close-btn"><span class="icon flaticon-cancel-1"></span></div>

    <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
    <nav class="menu-box">
      <div class="nav-logo"><a href="index-2.html"><img src="<%= asset_path "logo.png" %>" alt="" title=""></a></div>

      <ul class="navigation clearfix"><!--Keep This Empty / Menu will come through Javascript--></ul>
    </nav>
  </div><!-- End Mobile Menu -->
</header>

<% end %>